# 线上配置文件

server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.22.221/my_db
    username: root
    password: 74@1giC#yGDm1
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: I#3nyGDm1isphP
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://111.231.22.221:9200
    username: root
    password: isphPD9f07
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''